#include "HtmlReportWriter.h"
#include <fstream>
#include <iostream>

void HtmlReportWriter::writeReport(const std::string& filename, const std::vector<Insight>& insights) {
    std::ofstream file(filename);

    if (!file.is_open()) {
        std::cerr << "Error: Could not open " << filename << std::endl;
        return;
    }

    // HTML generation
    file << R"(
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Insight Report</title>
    <style>
        /* SETUP */
        body { font-family: sans-serif; margin: 40px; background-color: #ffffff; color: #333; }
        h1 { border-bottom: 2px solid #333; padding-bottom: 10px; }

        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #f2f2f2; font-weight: bold; }

        /* ESTABLISH RATING COLOR CODES */
        .rating-high { color: green; font-weight: bold; }
        .rating-med  { color: orange; font-weight: bold; }
        .rating-low  { color: red; font-weight: bold; }
    </style>
</head>
<body>
    <h1>Insight Analysis Results</h1>
    <p>Generated by statstack Insights Finder</p>

    <table>
        <thead>
            <tr>
                <th style="width: 15%;">Rating</th>
                <th>Insight Description</th>
            </tr>
        </thead>
        <tbody>
    )";

    // loop through Insights
    for (const auto& item : insights) {
        std::string ratingClass = "rating-low";
        if (item.rating >= 70.0) {
            ratingClass = "rating-high";
        } else if (item.rating >= 40.0) {
            ratingClass = "rating-med";
        }
        // generate a table row
        file << "<tr>";
        file << "<td class='" << ratingClass << "'>" << item.rating << "%</td>";
        file << "<td>" << item.text << "</td>";
        file << "</tr>\n";
    }

    // close HTML
    file << R"(
        </tbody>
    </table>
</body>
</html>
    )";
    file.close();
    std::cout << "Report generated: " << filename << std::endl;
}